### ISSUE TITLE
1.4.0 not found

### ISSUE THREAD

**Issue by teebu** [devmasx/merge-branch#16]
Can't use latest version 1.4.0 in my gh action. Throws error.

Using
```
  name: Merge branch
  uses: devmasx/merge-branch@1.4.0
```

**Comment by spacewaterbear** [comment]
replace ` uses: devmasx/merge-branch@1.4.0` by  `uses: devmasx/merge-branch@**master**`

**Comment by CWSites** [comment]
When trying to target a specific release you need to include the full name, in this case `v1.4.0` is what you need there. However @spacewaterbear is correct, by including `master` you will always be on latest.

See more on the [releases page](https://github.com/devmasx/merge-branch/releases)

**Comment by mmospanenko** [comment]
you have typo in version `v1.4.0`, not `1.4.0`

**Comment by teebu** [comment]
You're correct, issue resolved.
